version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: default
    ports:
      - "5432:5432"

  flyway-migrate:
    image: flyway/flyway:latest
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - postgres
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/default
      - FLYWAY_USER=admin
      - FLYWAY_PASSWORD=password123
      - FLYWAY_SCHEMAS=public
    command: ["migrate"]
