name: Docker Build, Publish and Static Analysis

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

     # - name: Set up Docker Build
     #   uses: docker/setup-buildx-action@v1

     # - name: Login to DockerHub
    #    run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      #  env:
     #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    #  - name: Build Docker image
     #   run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mdp-c1:latest ./src
    #    env:
     #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

   #   - name: Push Docker image to DockerHub
     #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mdp-c1:latest
   #     env:
    #      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    #  - name: Checkout code
     #   uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r src/requirements.txt
        
      - name: Snyk Code Analysis
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_API_TOKEN }}
          snyk test --file=src/requirements.txt --command=python3

      # SonarCloud analysis step
      - name: SonarCloud Analysis
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization_key \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONARCLOUD_TOKEN
        env:
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      - name: Run your Python tests
        run: python -m unittest discover -s tests
